theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: altshiftfestival.org
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo-dark.png"
  search:
    active: true
  debug:
     productionUrl: "https://www.altshiftfestival.org"